sonar.projectKey=bitzl_iiif-binder
# sonar.organization=bitzl

# relative paths to source directories. More details and properties are described
# at https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/ 
sonar.sources=.
